--app=Ver_2_Tests --port=1886 --group=4 --data=127.0.0.1:6379 --edge=1 --long=17.6264 --lat=64.547 --localregistryhost=0 --device

------

Current Device Node Id: e5e05664-f45b-4f45-b65d-9765da01f6d6

Starting App..

Program completed.


WARNING: There are no Local Registries listed on the network!


Doing multicast search for local registries

Calling compyou.. 

STDERR: 
node:internal/event_target:1012
  process.nextTick(() => { throw err; });
                           ^
STDERR: UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "network error".
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:300:10)
    at [kOnMessage] (node:internal/worker:311:37)
    at MessagePort.<anonymous> (node:internal/worker:212:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:737:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28) {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v18.16.0
Killing broker with PID: 110976




Test: jt6 Completed Succesfully
Time to Compile: 14.627s
Time to Run Test: 10.008s
